name: "Prepare"
description: "Prepare and tests the project"

inputs:
  sdk-version:
    description: "Dart SDK version"
    required: false
    default: "stable"

runs:
  using: "composite"
  steps:
  
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ inputs.sdk-version }}

    - name: Cache Dart dependencies
      uses: actions/cache@v3
      with:
        path: "~/.pub-cache"
        key: ${{ runner.os }}-dart-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-dart-

    - name: Get dependencies
      run: dart pub get
      shell: bash

    - run: dart pub global activate grinder
      shell: bash

    - name: Build version
      run: dart pub global run grinder:build-version
      shell: bash

    - name: Analyze
      run: dart analyze --fatal-infos --fatal-warnings .
      shell: bash
