name: Deploy Macos

on:
    workflow_dispatch:

jobs:
    deploy-macos:
        name: Deploy (Macos)
        runs-on: macos-latest
        env:
            PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
            GITHUB_BEARER_TOKEN: ${{ secrets.HOMEBREW_FVM_GH_TOKEN }}

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Prepare environment
          uses: ./.github/actions/prepare

        - name: Deploy Github Mac
          run: dart run grinder pkg-github-macos