# This is a basic workflow that is manually triggered

name: Homebrew Deploy

on:
  workflow_dispatch:
  release:
    types: [released]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  common:
    uses: ./.github/workflows/common.yml
  deploy:
    name: Deploy Homebrew
    needs: common
    runs-on: ubuntu-latest
    env:
      PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      GITHUB_TOKEN: ${{ secrets.HOMEBREW_FVM_GH_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Dart
        uses: DanTup/gh-actions/setup-dart@master
        with:
          channel: stable

      - name: Install dependencies
        run: dart pub get

      - name: Deploy to Homebrew
        run: dart pub run grinder pkg-homebrew-update
