name: Deploy Release

on:
  workflow_dispatch:
    inputs:
      jobToRun:
        description: 'Which job to run?'
        required: true
        default: 'all'
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    env:
      PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare

      - name: Deploy Github
        run: dart run grinder pkg-github-release

      - name: Deploy Github Linux
        run: dart run grinder pkg-github-linux

      - name: Deploy to Pub
        run: dart run grinder pkg-pub-deploy

  deploy-windows:
    name: Deploy (Windows)
    needs: release
    runs-on: windows-latest
    env:
      CHOCOLATEY_TOKEN: ${{ secrets.CHOCOLATEY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare

      - name: Deploy Github Windows
        run: dart run grinder pkg-github-windows

      - name: Deploy Chocolatey (Windows)
        run: dart run grinder pkg-chocolatey-deploy

  deploy-homebrew:
    name: Deploy (Mac)
    runs-on: ubuntu-latest
    needs: release
    env:
      PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare

      - name: Deploy Github Mac
        run: dart run grinder pkg-github-macos

      - name: Deploy to Homebrew
        run: dart run grinder pkg-homebrew-update

  # deploy-docker:
  #   name: Docker Deploy (latest)
  #   runs-on: ubuntu-latest
  #   needs: release
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Prepare environment
  #       uses: ./.github/actions/prepare

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and push (latest)
  #       id: docker_build_latest
  #       uses: docker/build-push-action@v5
  #       with:
  #         file: ./.docker/Dockerfile
  #         push: true
  #         tags: leoafarias/fvm:{{ github.event.release.tag_name }}
