name: Create Release

on:
  workflow_dispatch:
  release:
    types: [published, released]

jobs:
  common:
    uses: ./.github/workflows/common.yml
  release:
    name: Release
    needs: common
    runs-on: ubuntu-latest
    env:
      PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1.5.0

      - run: dart pub get

      - name: Deploy Github
        run: dart pub run grinder pkg-github-all

      - name: Deploy to Pub
        run: dart pub run grinder pkg-pub-deploy
