name: Test CLI

on:
  pull_request:
    paths-ignore:
      - "website/**"
      - "README.md"
      - "CHANGELOG.md"

jobs:
  test:
    name: "${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        sdk-version: [stable] #, dev]
        include:
          - os: macOS-latest
            TARGET: macos
          - os: ubuntu-latest
            TARGET: linux
          - os: windows-latest
            TARGET: windows

    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v1.5.0
      - name: Cache Dart dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache"
          key: ${{ runner.os }}-dart-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-dart-

      - run: dart pub get

      - run: dart pub run build_runner build --delete-conflicting-outputs
      - run: dart analyze --fatal-infos --fatal-warnings .

      - name: Generate git cache
        run: ./bin/fvm.dart install master

      - run: dart test
