name: Test CLI

on:
  workflow_call:
    inputs:
      sdk-version:
        description: "Dart SDK version"
        type: string
        required: false
        default: "stable"

  pull_request:
    paths-ignore:
      - "website/**"
      - "README.md"
      - "CHANGELOG.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Prepare environment
        uses: ./.github/actions/prepare
        with:
          sdk-version: ${{ github.event.inputs.sdk-version }}

      - name: Tests
        uses: ./.github/actions/test
