name: Test CLI

on:
  workflow_call:
    inputs:
      sdk-version:
        description: "Dart SDK version"
        type: string
        required: false
        default: "stable"

  pull_request:
    paths-ignore:
      - "website/**"
      - "README.md"
      - "CHANGELOG.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Initial test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare
        with:
          sdk-version: ${{ github.event.inputs.sdk-version }}

      - name: Run tests
        run: dart test --coverage=coverage
        shell: bash

      - name: Generate coverage reports
        run: grind coverage
        shell: bash

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-os:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare
        with:
          sdk-version: ${{ github.event.inputs.sdk-version }}

      - name: Tests
        uses: ./.github/actions/test
